# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 544cf17ba498ba7d6dd9fc2f58f04016cb7480856ed8e20d8acd4608f44a5e916e91113e9997c142e83c64e5b969a20ef76b437057842d64dffdd3598b66384b

test:
  secret_key_base: 1a56ba3c4718fc0544827a431ca52e99f51db1d560ccc830a559e98fa7c74101e819ec31b6e84c9df0329bed4ccfd89b4199f3e102e8414044019d0e8941a662

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
